### PR TITLE
Keep pillar attribute in vec_restore()

### PR DESCRIPTION
**Pull request by krlmlr**
Required for `vec_slice()`. Follow-up to #275.

### CODE REVIEW

**Comment by krlmlr** [comment]
macOS devel doesn't have binaries for udunits2, otherwise builds look good.

**Comment by krlmlr** [comment]
See https://pillar.r-lib.org/dev/articles/numbers.html#units for a demo, I quite like it! We can set display options on a units object, it survives arithmetics.

**Comment by Enchufa2** [comment]
Could yo please rebase/merge current master? I've added a workflow to check `quantities` on PR.

**Comment by Enchufa2** [comment]
All good, thanks!

**Pull request merged**
