### PR TITLE
remove deprecations, bump minor version

### PR DESCRIPTION
**Pull request by Enchufa2**
This removes `as.units`, `as_cf`, `make_unit` and `parse_unit`, which have been deprecated for a long time (since v0.5, 2018-01-07), and consequently bumps version to 0.7-0. I removed all calls and mentions to them in docs, demos and tests.

I think it's time to remove `ud_units` too, which is unneeded and soft-deprecated since v0.5 as well (and it only generates confusion, e.g. #211), but I wanted to ask you @edzer first.

### CODE REVIEW

**Comment by edzer** [comment]
Good idea. What was again the reason to deprecate `ud_units`, do we no longer use it? I mention it in the vignette, that would need updating too.

**Comment by Enchufa2** [comment]
Prior to v0.5-0, `ud_units` was internally used by `set_units` and `as_units`. NEWS for v0.5-0 said:

> `ud_units` is no longer necessary and is soft-deprecated, and may be removed in a future release.

**Comment by edzer** [comment]
OK, let's pull the plug. I'll update that vignette.

**Comment by Enchufa2** [comment]
Ok, plug pulled in the commit referenced above. I've removed:

- the private `sysdata.rda`;
- all the code associated;
- the few tests associated;
- all the examples in docs, demos and the other vignette.

I've converted every appearance of `with(ud_units, someunit)` to `make_units(someunit)`.

**Comment by edzer** [comment]
Great!

**Pull request merged**
