### PR TITLE
Support for logarithms

### PR DESCRIPTION
**Pull request by Enchufa2**
Initial implementation to address issues in #176.

### CODE REVIEW

**Comment by Enchufa2** [comment]
@edzer, @t-kalinowski: I think this PR is ready. Please, take a look. Summary:

- Logarithms now work via udunits2.
- `BW` (bel-Watts) and others are defined by udunits2, but not `B` (bel). With this PR, by default `B` is added, unless a user-provided XML database defines some `B` already or it's disabled via the `define_bel` option.
- Some tests and docs (see `help(Math.units)`) about the behaviour of the logarithm have been added.

If you agree with the changes so far, we can merge this PR and close #176. Maybe the best is to avoid any automatic conversion (to dBW, etc.) at the moment: we can always revisit the discussion in #176 if the users demand that feature.

**Comment by t-kalinowski** [comment]
By the way, I find your recent comments in #176 convincing, and I think it's probably OK to do automatic conversion.

**Comment by Enchufa2** [comment]
Nooo... Did we convince each other? :D :D :D

**Comment by Enchufa2** [comment]
Ok, I've added a couple of tests for the decibel too. May I squash and merge this, @edzer?

**Comment by edzer** [comment]
Yes, very good - go ahead. Great work!!

**Pull request merged**
