### PR TITLE
alternative solution to #89; #91

### PR DESCRIPTION
**Pull request by t-kalinowski**
With this implementation, the symbolic units are preserved so they can be printed correctly, and assigning a unit like "mg/kg" no longer changes the numeric value of the target vector.

Also, fixes the regression mentioned here (and elsewhere):
https://github.com/r-quantities/units/pull/64#issuecomment-339036324

### CODE REVIEW

**Comment by t-kalinowski** [comment]
Not quite complete yet. With units like `"20 * g /kg"`, the "20" gets discarded, which instead it should throw an error. It should be a simple 1 line fix, but there is no way to write any unit tests for this until #95 gets resolved.

**Comment by t-kalinowski** [comment]
ready for review

**Comment by edzer** [comment]
Thanks! I'm reluctant to merge this, as we still see conversion:
```r
> set_units(1, kg/g) + set_units(2)
1.002 kg/g
> set_units(1, kg/g) + set_units(1, "rad")
1.001 kg/g
```
and simplification when created from expressions involving units:
```r
> set_units(1, kg) / set_units(2, g)
500 1
```
I think simplification is wanted, and the way to go is that of the Flater paper. In case of a unitless unit, we need to keep where it comes from: `m/m` can be added to `rad`, but `s/s` not. I guess this calls for an additional field in the `symbolic_units` class.

There are a couple of other things in this PR that I will integrate manually.

As usual, I'll be happy to discuss.

**Comment by edzer** [comment]
So it seems I now have merged this; however, I didn't plan to. What a day.

**Comment by Enchufa2** [comment]
:D I apologise for my share. I feel I'm abusing a little bit your units day.

**Comment by edzer** [comment]
No, no, everything is fine - I see where you're going, very useful.

I reverted back to before the merge of this PR, merge master again and did a `git push -f` in branch `udunits`. This means that this PR has not been merged. Sorry for the mess!

**Comment by t-kalinowski** [comment]
haha. 

For what it's worth, here is a quick response to your concerns:
This is designed to address the specific case of creating a unit like "ug/kg", so that you could do, for example, conversion to "mg/kg", without simplification to `unitless` occurring (exactly the use case in the linked to issue, and also a use case that I think is very common.) 

The other use cases I think are mostly orthogonal to this PR.

I think that it's entirely reasonable that simplification occurs when multiplying or dividing per-existing unit objects outside the `as_units` constructor (and, more often than not, simplification is desirable, I think). To prevent simplification during arithmetic, a solution is to encourage users to create custom units like "ug_Arsenic / kg_soil". The issue of arithmetic between conceptually incompatible `unitless` units, like rad and kg/g, I think is also solved by recommending the creation of custom units.

**Comment by t-kalinowski** [comment]
Also, the current solution that allows for construction of units like "mg/kg", changes the value of the number vector on `units(x) <- "ug/kg"`, and I don't think that's right. This should always return `TRUE`
``` R
identical(x, drop_units(set_units(x, un)))
# should return true for all `x` and `un`
```

**Comment by edzer** [comment]
We now have
```r
> a = 1:10
> units(a) <- "ug/kg"
Error: In ‘ug/kg’ the numeric multiplier ‘1e-09’ is invalid. 
Use `install_conversion_constant()` to define a new unit that is a multiple of another unit.
> units(a) <- "ppm"
> a
Units: ppm
 [1]  1  2  3  4  5  6  7  8  9 10
> a + set_units(1)
Units: ppm
 [1] 1000001 1000002 1000003 1000004 1000005 1000006 1000007 1000008 1000009
[10] 1000010
```
I'm not so optimistic about the ability to add new units into udunits C API: they are either unitless and can then be added to any other unitless, or compatible to one of the existing units. A "new" unit is only meant for something really new (not compatible with the 7 SI base units); if you have weights of Arsenic, it is a weight, and can be added to any other weight.

**Pull request merged**
